### ISSUE TITLE
board announcement creates a PHPBB error message that shuts extensions down

### ISSUE THREAD

**Issue by arnehulstein** [phpbb-extensions/boardannouncements#129]
When I activated the boardannouncement extension, this was the error message I received:

==

phpBB is een foutmelding tegengekomen tijdens het bouwen van de container, veroorzaakt door een geïnstalleerde extensie. Om deze reden zijn alle extensies tijdelijk uitgeschakeld. Probeer de cache van je forum te legen. Alle extensies worden automatische ingeschakeld als de foutmelding is opgelost. Als deze foutmelding zich blijft voordoen, bezoek dan ons support forum via phpbb.nl.

Uitzondering: The file "/home/noppenforum/board.noppenforum.nl/ext/phpbb/boardannouncements/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 5 (near "- @config").
#0 /home/noppenforum/board.noppenforum.nl/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/noppenfor...')
#1 /home/noppenforum/board.noppenforum.nl/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /home/noppenforum/board.noppenforum.nl/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /home/noppenforum/board.noppenforum.nl/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /home/noppenforum/board.noppenforum.nl/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /home/noppenforum/board.noppenforum.nl/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /home/noppenforum/board.noppenforum.nl/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /home/noppenforum/board.noppenforum.nl/phpbb/di/container_builder.php(212): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /home/noppenforum/board.noppenforum.nl/common.php(115): phpbb\di\container_builder->get_container()
#9 /home/noppenforum/board.noppenforum.nl/adm/index.php(23): require('/home/noppenfor...')
#10 {main}

**Comment by DavidIQ** [comment]
Not sure where you got the extension from, but the services file in this repo is correct. For further support please visit our forum: https://github.com/phpbb-extensions/boardannouncements#support
