### ISSUE TITLE
[Request] Add an option to show BA on index page only

### ISSUE THREAD

**Issue by rxu** [phpbb-extensions/boardannouncements#74]
There's an option request to show the board announcement <a href="https://www.phpbb.com/customise/db/extension/boardannouncements/support/topic/135161">on index page only</a>.

**Comment by VSEphpbb** [comment]
I'm not sold on the idea of that. The forum index is not always the main landing page/entry point to a site, especially for new visitors. There's a greater chance an announcement will get missed if it's only on the index page, and I think index-only messages have been used more for stuff like a welcome message. And obviously we made it dismissiable so once seen, it wouldn't have to follow the user around from page to page and be annoying. :scream: 

Users should provide compelling reasons for why we should add another option, I think. I'd hate for ACP option creep :hushed:

**Comment by PayBas** [comment]
Agree with @VSEphpbb
