### ISSUE TITLE
New Users Don't See Current Announcement

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/boardannouncements#87]
When a new user is created, their board_announcement_status is 0 by default. So BA thinks they dismissed the announcement, so they don't see it anymore after they registered.

We need to set the users board_announcements_status to 1 when a user is created if board announcements config is enabled.

@rxu I think you've done something like this before, with an event during user creation.

https://www.phpbb.com/customise/db/extension/boardannouncements/support/topic/146966

**Comment by rxu** [comment]
@VSEphpbb I guess changing the default value of the ```board_announcements_status``` field from 0 to 1 should be sufficient, shouldn't it?

**Comment by VSEphpbb** [comment]
Something like you did here: https://github.com/phpbb-extensions/collapsible-categories/pull/24

**Comment by rxu** [comment]
Ah, ok.

**Comment by rxu** [comment]
Although, for CC we did that because for the ```TEXT``` field type default value can't be set, while for bool type it's possible.

**Comment by VSEphpbb** [comment]
OK, try it via migration first and lets see
