### ISSUE TITLE
phpBB DB error prevent from downloading your mode

### ISSUE THREAD

**Issue by Aliance** [phpbb-extensions/boardannouncements#90]
Trying to install your mode

> # Install

>  1. Download the latest validated release.

gave me an error:

> General Error
> SQL ERROR [ mysqli ]

> Unknown database 'phpbb' [1049]

> An sql error occurred while fetching this page. Please contact an administrator if this problem persists.

Is there any mirrors for downloading?

**Comment by DavidIQ** [comment]
Ummm...github itself has all the code so you can just download it from here.  Needs to be unzipped into a phpbb/boardannouncements directory format and placed in the ext directory.
